version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: typedoc
    versions:
    - 0.20.20
    - 0.20.28
    - 0.20.7
  - dependency-name: "@types/node"
    versions:
    - 14.14.17
  - dependency-name: ava
    versions:
    - 3.14.0
